var projects = {
  cubeworld:{
    video:"cubeworld.mp4",
    desc:"loldesc",
    improvements:"lolimprovements",
    technologies:"loltechnologies",
  },
  resohm:{
    video:"resohm.mp4",
    desc:"loldesc",
    improvements:"lolimprovements",
    technologies:"loltechnologies",
  },
  libero:{
    video:"libero.mp4",
    desc:"loldesc",
    improvements:"lolimprovements",
    technologies:"loltechnologies",
  },
  trendify:{
    video:"trendify.mp4",
    desc:"loldesc",
    improvements:"lolimprovements",
    technologies:"loltechnologies",
  },
  map:{
    video:"map.mp4",
    desc:"loldesc",
    improvements:"lolimprovements",
    technologies:"loltechnologies",
  },
  plant:{
    video:"movie.mp4",
    desc:"loldesc",
    improvements:"lolimprovements",
    technologies:"loltechnologies"
  }
}
